export const GET_BY_EMAIL_PAYMENT_REQUEST = 'GET_BY_EMAIL_PAYMENT_REQUEST';
export const GET_BY_EMAIL_PAYMENT_SUCCESS = 'GET_BY_EMAIL_PAYMENT_SUCCESS';
export const GET_BY_EMAIL_PAYMENT_FAIL = 'GET_BY_EMAIL_PAYMENT_FAIL';