export const USER_INFOBYID_REQUEST = 'USER_INFOBYID_REQUEST';
export const USER_INFOBYID_SUCCESS = 'USER_INFOBYID_SUCCESS';
export const USER_INFOBYID_FAIL = 'USER_INFOBYID_FAIL';

export const UPDATE_USER_INFOBYID_REQUEST = 'UPDATE_USER_INFOBYID_REQUEST';
export const UPDATE_USER_INFOBYID_SUCCESS = 'UPDATE_USER_INFOBYID_SUCCESS';
export const UPDATE_USER_INFOBYID_FAIL = 'UPDATE_USER_INFOBYID_FAIL';